apiVersion: v1
kind: Service
metadata:
  name: furniture-frontend
spec:
  selector:
    app: furniture-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
