apiVersion: v1
kind: Service
metadata:
  name: furniture-frontend
spec:
  selector:
    app: furniture-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer